// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Recipe struct {
	ID         string `json:"id"`
	RecipeName string `json:"recipe_name"`
}

type RecipeInput struct {
	RecipeName string `json:"recipe_name"`
}

type RecipeRole struct {
	ID       string `json:"id"`
	RecipeID string `json:"recipe_id"`
	UserID   string `json:"user_id"`
	Relation string `json:"relation"`
}
