// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddIngredientInput struct {
	Name string `json:"name"`
}

type AddPantryItemInput struct {
	IngredientID string `json:"ingredientId"`
	Quantity     *int   `json:"quantity,omitempty"`
}

type AddRecipeInput struct {
	Name string `json:"name"`
}

type Ingredient struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type PantryItem struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
	Unit     string `json:"unit"`
}

type Recipe struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type RecipeRole struct {
	ID       string `json:"id"`
	RecipeID string `json:"recipeId"`
	UserID   string `json:"userId"`
	Relation string `json:"relation"`
}

type UpdatePantryItemInput struct {
	ID       string `json:"id"`
	Quantity *int   `json:"quantity,omitempty"`
}

type UpdateRecipeInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
