name: Build & Push
run-name: ${{ github.actor }} is pushing a new image
on:
  workflow_dispatch:
env:
  AWS_REGION: 'eu-north-1'
  AWS_ROLE: 'arn:aws:iam::044984945511:role/github_actions_role'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          disable-retry: true
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push artifact to ECR
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/recipe-maker:latest .
          docker push ${{ steps.login-ecr.outputs.registry }}/recipe-maker:latest
